const responseConstants = {
    SUCCESS : 200,
    INVALID_ACCESS_TOKEN : 108,
    TOKEN_EXPIRED : 109,
    INVALID_PASSWORD : 110,
    INVALID_USER_CREDENTIALS : 111,
    EMAIL_ALREADY_EXIST : 112,
    PASSWORD_AND_CNF_PASSWORD_SHOULD_BE_SAME : 113,
    INVALID_REFRESH_TOKEN : 114,
    USER_NOT_FOUND : 115,
    REFRESH_TOKEN_MISMATCHED : 116,
    REFRESH_TOKEN_EXPIRED : 117,
    INVALID_USER_TOKEN : 118,
    TITLE_ALREADY_EXIST : 119,
    TASK_NOT_FOUND : 120,
    REFRESH_TOKEN_NOT_PROVIDED : 121

}

export default responseConstants;